### ISSUE TITLE
Bypasses,False flags

### ISSUE THREAD

**Issue by tombola46** [Monstercide/Storm-Anticheat#4]
Bypasses-Hack client: Skid - Step (AAC 3.3.5)
                                   Skid - Speed (NCP Bhop, Spartan YPort, Spartan BHop)
                                   Skid - LongJump (AAC 3.3.0)
False flags - AimBot(Flagging when legit hitting, flagging when i am not using aimbot or killaura, flagging when flying with /fly)

**Comment by Monstercide** [comment]
Fixed in v2.0.7
